//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "genre")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Text")]
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::game_genre::Entity")]
    GameGenre,
}

impl Related<super::game_genre::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GameGenre.def()
    }
}

impl Related<super::game::Entity> for Entity {
    fn to() -> RelationDef {
        super::game_genre::Relation::Game.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::game_genre::Relation::Genre.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
