//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

pub use super::developer::Entity as Developer;
pub use super::game::Entity as Game;
pub use super::game_genre::Entity as GameGenre;
pub use super::game_tag::Entity as GameTag;
pub use super::genre::Entity as Genre;
pub use super::session::Entity as Session;
pub use super::tag::Entity as Tag;
